title: Status updates
author: Konstantinos Chorianopoulos
email: status@epidro.me
description: >- # this means to ignore newlines until "baseurl:"
  This is a microblog (twitter clone) with status updates about
  various topics. You can follow the updates with the RSS feed, or
  you can contribute to the Github repository.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username: epidrome
keybase_username: epidrome

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
show_excerpts: true
header_pages:
  - readme.markdown

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-archives

permalink: /:slug

jekyll-archives:
  enabled: [tags]
  layout: archive
  permalinks:
    tag: '/tag/:name/'

defaults:
  -
    scope:
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "status"
