title: Status updates
author: 
  name: Konstantinos Chorianopoulos
  email: status@epidro.me
description: >- # this means to ignore newlines until "baseurl:"
  Microblog (similar to Twitter, minus the hate) with 
  status updates about various topics. You can follow the 
  updates with the RSS feed, email a private message, or
  post a public comment by oppening a github issue.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  social_links:
    github: epidrome
  date_format: "%b %-d, %Y"
show_excerpts: true
header_pages:
  - readme.markdown

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-archives
  - kramdown-parser-gfm

permalink: /:slug

jekyll-archives:
  enabled: [tags]
  layout: archive
  permalinks:
    tag: '/tag/:name/'

defaults:
  -
    scope:
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "status"
